"use client"

import { useState, useEffect } from "react"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import {
    Calendar,
    Clock,
    User,
    Phone,
    Mail,
    AlertTriangle,
    Heart,
    ArrowLeft,
    FileText,
    Shield,
    Pill,
    X,
    Video,
    Link as LinkIcon,
    Copy,
} from "lucide-react"
import Link from "next/link"
import { format } from "date-fns"
import { getAppointment, updateAppointment } from "@/lib/actions/appointment.actions"
import { useParams } from "next/navigation"
import { getDoctorById, getRegisteredPatient, getUser } from "@/lib/actions/patient.actions"
import AppointmentModal from "@/components/ui/AppointmentModal"
import { toast } from "@/hooks/use-toast"
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog"
import { Label } from "@/components/ui/label"
import { Switch } from "@/components/ui/switch"
import { Input } from "@/components/ui/input"

// Helper function to format date
const formatDate = (dateString) => {
    try {
        return format(new Date(dateString), "PPP")
    } catch (error) {
        return "Invalid date"
    }
}

// Helper function to format time
const formatTime = (dateString) => {
    try {
        return format(new Date(dateString), "h:mm a")
    } catch (error) {
        return "Invalid time"
    }
}

export default function PatientDetails() {
    const [patient, setPatient] = useState(null)
    const [appointment, setAppointment] = useState(null)
    const [loading, setLoading] = useState(false)
    const [isLoading, setIsLoading] = useState(false)
    const [cancelModel, setCancelModel] = useState(false)
    const [openModel, setOpenModel] = useState(false)
    const [virtualMeetingModal, setVirtualMeetingModal] = useState(false)
    const [meetingLink, setMeetingLink] = useState("")
    const [isVirtual, setIsVirtual] = useState(false)
    const params = useParams()
    const id = params?.id

    useEffect(() => {
        const fetchPatientData = async () => {
            if (!id) return

            setLoading(true)
            try {
                const fetchedAppointment = await getAppointment(id)
                const fetchedPatient = await getRegisteredPatient(fetchedAppointment?.userId)

                setPatient(fetchedPatient)
                if (fetchedAppointment) {
                    setAppointment(fetchedAppointment)
                    setIsVirtual(fetchedAppointment.isVirtual || false)
                    setMeetingLink(fetchedAppointment.meetingLink || "")
                }
            } catch (error) {
                console.error("Error fetching patient data:", error)
                toast({
                    title: "Error",
                    description: "Failed to load patient data",
                    variant: "destructive",
                })
            } finally {
                setLoading(false)
            }
        }

        fetchPatientData()
    }, [id])

    // Generate a default meeting link
    const generateDefaultLink = () => {
        const defaultLink = `https://meet.jit.si/MediNexus-${patient?.name?.replace(/\s+/g, "-")}-${format(new Date(), "yyyy-MM-dd")}`;
        setMeetingLink(defaultLink);
    }

    // Auto-generate meeting link when virtual is toggled on
    useEffect(() => {
        if (isVirtual && !meetingLink && patient?.name) {
            generateDefaultLink();
        }
    }, [isVirtual, patient]);

    // Handle toggle change with auto-generation
    const handleVirtualToggle = (checked) => {
        setIsVirtual(checked);
        // If turning on virtual and no link exists, it will be generated by the useEffect
    }

    // Status badge color mapping
    const getStatusColor = (status) => {
        switch (status?.toLowerCase()) {
            case "completed":
                return "bg-green-500"
            case "pending":
                return "bg-amber-500"
            case "cancelled":
                return "bg-red-500"
            default:
                return "bg-gray-500"
        }
    }

    const handleUpdateAppointmentType = async () => {
        if (!appointment?._id) return

        setIsLoading(true)
        try {
            // Create the properly formatted params object that matches the server API
            const updateParams = {
                appointmentId: appointment._id,
                userId: appointment.userId,
                appointment: {
                    // Only include fields you want to update
                    isVirtual,
                    meetingLink: meetingLink,
                },
                type: "schedule"
            }

            const updatedAppointment = await updateAppointment(updateParams)
            setAppointment(updatedAppointment)

            // Show success toast for appointment update
            toast({
                title: "Success",
                description: `Appointment updated to ${isVirtual ? "virtual" : "in-person"} `,
                variant: "default",
            })

            try {
                const user = await getUser(updatedAppointment?.userId)
                const doctor = await getDoctorById(updatedAppointment?.primaryPhysician?.id)

                const response = await fetch("/api/email", {
                    method: "POST",
                    headers: { "Content-Type": "application/json" },
                    body: JSON.stringify({
                        email: user?.email,
                        name: updatedAppointment?.patientName,
                        appointmentDate: updatedAppointment?.timeSlot?.startTime,
                        reason: updatedAppointment?.reason,
                        doctorName: updatedAppointment?.primaryPhysician?.name,
                        type: "schedule",
                        meetingId: updatedAppointment?.meetingLink,
                        doctorEmail: doctor?.email
                    }),
                })

                const data = await response.json()

                if (data.success) {
                    console.log("Email notification sent");

                }
            } catch (error) {
                console.error("Error sending email notification:", error);

            }

            setVirtualMeetingModal(false)
        } catch (error) {
            console.error("Error updating appointment:", error)
            toast({
                title: "Error",
                description: "Failed to update appointment type",
                variant: "destructive",
            })
        } finally {
            setIsLoading(false)
        }
    }

    // Copy meeting link to clipboard
    const copyMeetingLink = () => {
        navigator.clipboard.writeText(appointment?.meetingLink || "");
        toast({
            title: "Copied",
            description: "Meeting link copied to clipboard",
            variant: "default",
        })
    }

    if (loading) {
        return (
            <div className="flex items-center justify-center h-screen">
                <div className="animate-spin rounded-full h-12 w-12 border-t-2 border-b-2 border-primary"></div>
            </div>
        )
    }

    return (
        <div className="w-full p-6 bg-background">
            <header className="mb-6">
                <Link href="/admin" className="text-primary flex items-center mb-3 hover:underline">
                    <ArrowLeft className="mr-2 h-4 w-4" />
                    Back to Dashboard
                </Link>
                <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between">
                    <h1 className="text-2xl font-bold">Patient Details</h1>
                    <div className="flex gap-3 mt-3 sm:mt-0">
                        <div className="flex gap-3 justify-center sm:ml-5">
                            {/* Virtual Meeting Button - Only show if appointment is virtual and has a meeting link */}
                            {appointment?.isVirtual && appointment?.meetingLink && (
                                <Button
                                    variant="outline"
                                    className="border-0 py-4 text-sm bg-teal-950 hover:bg-teal-900 shadow-xl hover:shadow-xl transition-all duration-100 
                                rounded-lg px-4 transform hover:scale-105 flex items-center justify-center gap-2"
                                    onClick={() => window.open(appointment.meetingLink, "_blank")}
                                >
                                    <Video className="h-4 w-4" />
                                    Join Video Call
                                </Button>
                            )}

                            {/* Virtual/In-person toggle button */}
                            <Button
                                variant="outline"
                                className="border-0 py-4 text-sm bg-teal-950 hover:bg-teal-900 shadow-xl hover:shadow-xl transition-all duration-100 
                            rounded-lg px-4 transform hover:scale-105 flex items-center justify-center gap-2"
                                onClick={() => setVirtualMeetingModal(true)}
                            >
                                {appointment?.isVirtual ? (
                                    <>
                                        <Video className="h-4 w-4" />
                                        Manage Virtual Meeting
                                    </>
                                ) : (
                                    <>
                                        <User className="h-4 w-4" />
                                        Set Appointment Type
                                    </>
                                )}
                            </Button>

                            <AppointmentModal
                                type="schedule"
                                patientId={patient?._id}
                                userId={appointment?.userId}
                                appointment={appointment}
                                onClose={() => setOpenModel(false)}
                            />
                            <AppointmentModal
                                type="cancel"
                                patientId={patient?._id}
                                userId={appointment?.userId}
                                appointment={appointment}
                                onClose={() => setOpenModel(false)}
                            />
                        </div>
                    </div>
                </div>
            </header>

            <div className="grid grid-cols-1 lg:grid-cols-12 gap-4 md:gap-6">
                {/* Sidebar - Patient Info */}
                <div className="lg:col-span-4 space-y-4">
                    {/* Patient Profile Card */}
                    <Card className="overflow-hidden border-none shadow-lg bg-gradient-to-br from-teal-950 to-teal-950">
                        <CardHeader className="bg-gradient-to-r from-teal-950 to-teal-950 pb-4">
                            <div className="flex items-center justify-between">
                                <CardTitle className="text-white font-medium">Patient Profile</CardTitle>
                                <Badge className="bg-gray-900 px-2 py-2 text-teal-50 font-medium border-none">
                                    {patient?.gender?.charAt(0).toUpperCase() + patient?.gender?.slice(1) || "Unknown"}
                                </Badge>
                            </div>
                        </CardHeader>

                        <CardContent className="pt-5">
                            <div className="flex items-center gap-4 mb-6 pb-4 border-b border-teal-900">
                                <div className="w-16 h-16 rounded-full bg-teal-900 flex items-center justify-center shadow-inner">
                                    <User className="h-8 w-8 text-white" />
                                </div>
                                <div>
                                    <h2 className="text-xl font-semibold text-white">{patient?.name || "Unknown"}</h2>
                                    <p className="text-teal-300">{patient?.age || "?"} years old</p>
                                </div>
                            </div>

                            <div className="space-y-5">
                                <div className="flex items-center text-white">
                                    <Phone className="h-4 w-4 text-teal-300 mr-3 flex-shrink-0" />
                                    <span className="truncate">{patient?.phone || "No phone"}</span>
                                </div>

                                <div className="flex items-center text-white">
                                    <Mail className="h-4 w-4 text-teal-300 mr-3 flex-shrink-0" />
                                    <span className="truncate">{patient?.email || "No email"}</span>
                                </div>

                                <div className="flex items-start">
                                    <AlertTriangle className="h-4 w-4 text-teal-300 mr-3 mt-1 flex-shrink-0" />
                                    <div className="text-white">
                                        <p className="font-medium">Emergency Contact</p>
                                        <p className="text-sm text-teal-300 mt-1">{patient?.emergencyContactName || "None"}</p>
                                        <p className="text-sm text-teal-300 mt-1">{patient?.emergencyContactNumber || "None"}</p>
                                    </div>
                                </div>

                                <div className="flex items-start">
                                    <FileText className="h-4 w-4 text-teal-300 mr-3 mt-1 flex-shrink-0" />
                                    <div className="text-white">
                                        <p className="font-medium">Identification</p>
                                        <p className="text-sm text-teal-300 mt-1">
                                            {patient?.identificationType}: {patient?.identificationNumber || "None"}
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </CardContent>
                    </Card>

                    {/* Insurance Information Card */}
                    <Card className="border-none shadow-lg bg-gradient-to-br from-teal-950 to-teal-950">
                        <CardHeader className="bg-gradient-to-r from-teal-950 to-teal-950 pb-3">
                            <CardTitle className="text-white font-medium">Insurance Details</CardTitle>
                        </CardHeader>

                        <CardContent className="pt-4">
                            <div className="space-y-4 text-white">
                                <div className="flex items-start">
                                    <Shield className="h-4 w-4 text-teal-300 mr-3 mt-1 flex-shrink-0" />
                                    <div>
                                        <p className="font-medium">Provider</p>
                                        <p className="text-sm text-teal-300">{patient?.insuranceProvider || "None registered"}</p>
                                    </div>
                                </div>

                                <div className="flex items-start">
                                    <FileText className="h-4 w-4 text-teal-300 mr-3 mt-1 flex-shrink-0" />
                                    <div>
                                        <p className="font-medium">Policy Number</p>
                                        <p className="text-sm text-teal-300">{patient?.insurancePolicyNumber || "N/A"}</p>
                                    </div>
                                </div>

                                <div className="flex justify-end mt-4">
                                    <Button variant="outline" size="sm" className="bg-teal-900 hover:bg-teal-900 border-none text-white">
                                        View Full Details
                                    </Button>
                                </div>
                            </div>
                        </CardContent>
                    </Card>
                </div>

                {/* Main Content Area */}
                <div className="lg:col-span-8 space-y-4 md:space-y-6">
                    {/* Current Appointment Card */}
                    <Card className="border-none shadow-lg bg-gradient-to-br from-teal-950 to-teal-950">
                        <CardHeader className="bg-gradient-to-r from-teal-950 to-teal-950 pb-3 flex flex-row items-center justify-between">
                            <CardTitle className="text-white font-medium">Current Appointment</CardTitle>
                            <Badge className={`px-2 py-2 ${appointment?.status?.toLowerCase() === "completed" ? "bg-green-500 text-green-950" :
                                appointment?.status?.toLowerCase() === "pending" ? "bg-amber-500 text-amber-950" :
                                    appointment?.status?.toLowerCase() === "cancelled" ? "bg-red-500 text-red-950" :
                                        "bg-gray-900 text-white"
                                } font-medium border-none`}>
                                {appointment?.status?.charAt(0).toUpperCase() + appointment?.status?.slice(1) || "Unknown"}
                            </Badge>
                        </CardHeader>

                        <CardContent className="pt-4">
                            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                                <div className="space-y-4 text-white">
                                    <div className="flex items-center">
                                        <Calendar className="h-4 w-4 text-teal-300 mr-3 flex-shrink-0" />
                                        <div>
                                            <p className="font-medium">Date</p>
                                            <p className="text-sm text-teal-300">
                                                {formatDate(appointment?.timeSlot?.startTime) || "Not scheduled"}
                                            </p>
                                        </div>
                                    </div>

                                    <div className="flex items-center">
                                        <Clock className="h-4 w-4 text-teal-300 mr-3 flex-shrink-0" />
                                        <div>
                                            <p className="font-medium">Time</p>
                                            <p className="text-sm text-teal-300">
                                                {formatTime(appointment?.timeSlot?.startTime)} - {formatTime(appointment?.timeSlot?.endTime) || "TBD"}
                                            </p>
                                        </div>
                                    </div>

                                    <div className="flex items-center">
                                        <User className="h-4 w-4 text-teal-300 mr-3 flex-shrink-0" />
                                        <div>
                                            <p className="font-medium">Doctor</p>
                                            <p className="text-sm text-teal-300">
                                                {appointment?.primaryPhysician?.name || "Not assigned"}
                                            </p>
                                        </div>
                                    </div>

                                    <div className="flex items-center">
                                        {appointment?.isVirtual ? (
                                            <Video className="h-4 w-4 text-teal-300 mr-3 flex-shrink-0" />
                                        ) : (
                                            <User className="h-4 w-4 text-teal-300 mr-3 flex-shrink-0" />
                                        )}
                                        <div>
                                            <p className="font-medium">Type</p>
                                            <div className="flex items-center gap-2">
                                                <p className="text-sm text-teal-300">
                                                    {appointment?.isVirtual ? "Virtual Consultation" : "In-person Visit"}
                                                </p>
                                                {appointment?.isVirtual && (
                                                    <Badge className="bg-teal-900 text-white text-xs border-none">Online</Badge>
                                                )}
                                            </div>
                                        </div>
                                    </div>

                                    {/* Meeting Link (only if virtual) */}
                                    {appointment?.isVirtual && appointment?.meetingLink && (
                                        <div className="flex items-start">
                                            <LinkIcon className="h-4 w-4 text-teal-300 mr-3 mt-1 flex-shrink-0" />
                                            <div className="flex-1">
                                                <p className="font-medium">Meeting Link</p>
                                                <div className="flex items-center mt-1 gap-2">
                                                    <p className="text-xs text-teal-300 truncate max-w-[70%]">
                                                        {appointment.meetingLink}
                                                    </p>
                                                    <Button
                                                        variant="ghost"
                                                        size="sm"
                                                        className="h-6 px-2 bg-teal-900 hover:bg-teal-900 text-white"
                                                        onClick={copyMeetingLink}
                                                    >
                                                        <Copy className="h-3 w-3 mr-1" />
                                                        <span className="text-xs">Copy</span>
                                                    </Button>
                                                </div>
                                            </div>
                                        </div>
                                    )}
                                </div>

                                <div className="text-white">
                                    <h3 className="font-medium mb-2">Reason for Visit</h3>
                                    <div className="bg-teal-900/50 p-4 rounded-md border border-teal-900 shadow-inner mb-4">
                                        <p className="text-sm text-teal-200">
                                            {appointment?.reason || "No reason specified"}
                                        </p>
                                    </div>

                                    <div className="flex flex-wrap items-center gap-3 mt-4">
                                        <Badge className="bg-teal-900 text-white border-none">
                                            {appointment?.isVirtual ? "Virtual" : "In-person"}
                                        </Badge>
                                        <span className="text-xs text-teal-300">Created: {formatDate(appointment?.createdAt)}</span>
                                    </div>
                                </div>
                            </div>
                        </CardContent>
                    </Card>

                    {/* Medical Information Card */}
                    <Card className="border-none shadow-lg bg-gradient-to-br from-teal-950 to-teal-950">
                        <CardHeader className="bg-gradient-to-r from-teal-950 to-teal-950 pb-3">
                            <CardTitle className="text-white font-medium">Medical Information</CardTitle>
                        </CardHeader>

                        <CardContent className="pt-4">
                            <Tabs defaultValue="allergies" className="w-full">
                                <TabsList className="grid w-full grid-cols-3 mb-6 bg-teal-900 p-1 rounded-lg">
                                    <TabsTrigger
                                        value="medical-history"
                                        className="text-teal-200 data-[state=active]:bg-teal-900 data-[state=active]:text-white rounded-md transition-all"
                                    >
                                        Medical History
                                    </TabsTrigger>
                                    <TabsTrigger
                                        value="medications"
                                        className="text-teal-200 data-[state=active]:bg-teal-900 data-[state=active]:text-white rounded-md transition-all"
                                    >
                                        Medications
                                    </TabsTrigger>
                                    <TabsTrigger
                                        value="allergies"
                                        className="text-teal-200 data-[state=active]:bg-teal-900 data-[state=active]:text-white rounded-md transition-all"
                                    >
                                        Allergies & Alerts
                                    </TabsTrigger>
                                </TabsList>

                                <TabsContent value="medical-history" className="mt-0">
                                    <div className="space-y-4 text-white">
                                        <div className="bg-teal-900/50 p-4 rounded-lg border border-teal-900">
                                            <h3 className="font-medium flex items-center mb-3">
                                                <Heart className="h-4 w-4 text-teal-300 mr-2" />
                                                Past Medical History
                                            </h3>
                                            <p className="text-sm text-teal-200 bg-teal-900/30 p-3 rounded-md">
                                                {patient?.pastMedicalHistory || "No past medical history recorded"}
                                            </p>
                                        </div>

                                        <div className="bg-teal-900/50 p-4 rounded-lg border border-teal-900">
                                            <h3 className="font-medium flex items-center mb-3">
                                                <Heart className="h-4 w-4 text-teal-300 mr-2" />
                                                Family Medical History
                                            </h3>
                                            <p className="text-sm text-teal-200 bg-teal-900/30 p-3 rounded-md">
                                                {patient?.familyMedicalHistory || "No family medical history recorded"}
                                            </p>
                                        </div>
                                    </div>
                                </TabsContent>

                                <TabsContent value="medications" className="mt-0">
                                    <div className="bg-teal-900/50 p-4 rounded-lg border border-teal-900 text-white">
                                        <h3 className="font-medium flex items-center mb-3">
                                            <Pill className="h-4 w-4 text-teal-300 mr-2" />
                                            Current Medications
                                        </h3>
                                        <p className="text-sm text-teal-200 bg-teal-900/30 p-3 rounded-md">
                                            {patient?.currentMedication || "No current medications recorded"}
                                        </p>
                                    </div>
                                </TabsContent>

                                <TabsContent value="allergies" className="mt-0">
                                    <div className="space-y-4 text-white">
                                        <div className="bg-teal-900/50 p-4 rounded-lg border border-teal-900">
                                            <h3 className="font-medium flex items-center mb-3">
                                                <AlertTriangle className="h-4 w-4 text-teal-300 mr-2" />
                                                Allergies
                                            </h3>
                                            <p className="text-sm text-teal-200 bg-teal-900/30 p-3 rounded-md">
                                                {patient?.allergies || "No allergies recorded"}
                                            </p>
                                        </div>

                                        <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
                                            <div className="bg-teal-900/30 p-4 rounded-lg border border-teal-900 flex items-center">
                                                <Shield className="h-4 w-4 text-teal-300 mr-3 flex-shrink-0" />
                                                <div>
                                                    <p className="text-xs font-medium">Treatment Consent</p>
                                                    <Badge
                                                        className={`mt-1 ${patient?.treatmentConsent ? "bg-green-500 text-green-950" : "bg-red-500 text-red-950"
                                                            } border-none`}
                                                    >
                                                        {patient?.treatmentConsent ? "Provided" : "Not Provided"}
                                                    </Badge>
                                                </div>
                                            </div>

                                            <div className="bg-teal-900/30 p-4 rounded-lg border border-teal-900 flex items-center">
                                                <Shield className="h-4 w-4 text-teal-300 mr-3 flex-shrink-0" />
                                                <div>
                                                    <p className="text-xs font-medium">Disclosure Consent</p>
                                                    <Badge
                                                        className={`mt-1 ${patient?.disclosureConsent ? "bg-green-500 text-green-950" : "bg-red-500 text-red-950"
                                                            } border-none`}
                                                    >
                                                        {patient?.disclosureConsent ? "Provided" : "Not Provided"}
                                                    </Badge>
                                                </div>
                                            </div>

                                            <div className="bg-teal-900/30 p-4 rounded-lg border border-teal-900 flex items-center">
                                                <Shield className="h-4 w-4 text-teal-300 mr-3 flex-shrink-0" />
                                                <div>
                                                    <p className="text-xs font-medium">Privacy Consent</p>
                                                    <Badge
                                                        className={`mt-1 ${patient?.privacyConsent ? "bg-green-500 text-green-950" : "bg-red-500 text-red-950"
                                                            } border-none`}
                                                    >
                                                        {patient?.privacyConsent ? "Provided" : "Not Provided"}
                                                    </Badge>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </TabsContent>
                            </Tabs>
                        </CardContent>
                    </Card>
                </div>
            </div>

            {/* Virtual Meeting Modal */}
            <Dialog open={virtualMeetingModal} onOpenChange={setVirtualMeetingModal}>
                <DialogContent className="sm:max-w-md bg-teal-950 border-teal-900 shadow-xl">
                    <DialogHeader>
                        <DialogTitle className="text-teal-50">Appointment Type</DialogTitle>
                        <DialogDescription className="text-teal-300">
                            Configure appointment method and meeting details
                        </DialogDescription>
                    </DialogHeader>

                    <div className="space-y-6 py-4">
                        <div className="flex items-center justify-between p-4 bg-teal-900 rounded-lg">
                            <div className="space-y-1">
                                <Label className="text-teal-50">Virtual Appointment</Label>
                                <p className="text-sm text-teal-300">
                                    Enable for telehealth consultation
                                </p>
                            </div>
                            <Switch
                                checked={isVirtual}
                                onCheckedChange={handleVirtualToggle}
                                className="data-[state=checked]:bg-teal-600"
                            />
                        </div>

                        {isVirtual && (
                            <div className="space-y-3 p-4 bg-teal-900/50 rounded-lg border border-teal-800">
                                <Label htmlFor="meetingLink" className="text-teal-50">Meeting Link</Label>
                                <div className="flex gap-2">
                                    <Input
                                        id="meetingLink"
                                        value={meetingLink}
                                        onChange={(e) => setMeetingLink(e.target.value)}
                                        placeholder="https://meet.example.com/room-id"
                                        className="bg-teal-900 border-teal-800 text-teal-50 placeholder:text-teal-400"
                                    />
                                    <Button
                                        variant="outline"
                                        className="bg-teal-800 hover:bg-teal-700 border-teal-700 text-teal-50"
                                        onClick={generateDefaultLink}
                                    >
                                        Generate
                                    </Button>
                                </div>
                                <p className="text-xs text-teal-300">
                                    Patient will receive this link via email to join the virtual consultation
                                </p>
                            </div>
                        )}

                        {!isVirtual && (
                            <div className="p-4 bg-teal-900/30 border border-teal-800 rounded-lg">
                                <div className="flex items-start">
                                    <AlertTriangle className="h-4 w-4 text-teal-300 mr-2 mt-1 flex-shrink-0" />
                                    <div>
                                        <p className="text-sm font-medium text-teal-200">In-Person Appointment</p>
                                        <p className="text-xs text-teal-300 mt-1">
                                            The patient must attend in person at the clinic.
                                            They will be notified that virtual consultation is not available.
                                        </p>
                                    </div>
                                </div>
                            </div>
                        )}
                    </div>

                    <DialogFooter className="flex flex-col sm:flex-row gap-3">
                        <Button
                            variant="outline"
                            onClick={() => setVirtualMeetingModal(false)}
                            className="w-full sm:w-auto bg-teal-900 hover:bg-teal-800 border-teal-800 text-teal-50"
                        >
                            Cancel
                        </Button>
                        <Button
                            onClick={handleUpdateAppointmentType}
                            disabled={isLoading}
                            className="w-full sm:w-auto bg-teal-700 hover:bg-teal-600 text-teal-50"
                        >
                            {isLoading ? "Saving..." : "Save Changes"}
                        </Button>
                    </DialogFooter>
                </DialogContent>
            </Dialog>

            {/* Modal components (included but not visible initially) */}
            {openModel && (
                <AppointmentModal
                    type="schedule"
                    patientId={patient?._id}
                    userId={appointment?.userId}
                    appointment={appointment}
                    onClose={() => setOpenModel(false)}
                />
            )}

            {cancelModel && (
                <AppointmentModal
                    type="cancel"
                    patientId={patient?._id}
                    userId={appointment?.userId}
                    appointment={appointment}
                    onClose={() => setCancelModel(false)}
                />
            )}
        </div>
    );
}