/**
 * Advanced symptom-to-specialty mapping
 * This file contains additional mappings for more specific conditions and medical terms
 * Data compiled from medical resources and clinical guidelines
 */

import { SymptomMapping } from './symptomMapping';

export const advancedSymptomToSpecialtyMapping: SymptomMapping = {
  // Advanced Neurological conditions
  "amyotrophic lateral sclerosis": "Neurologist",
  "als": "Neurologist",
  "lou gehrig's disease": "Neurologist",
  "guillain-barré syndrome": "Neurologist",
  "myasthenia gravis": "Neurologist",
  "huntington's disease": "Neurologist",
  "dystonia": "Neurologist",
  "essential tremor": "Neurologist",
  "trigeminal neuralgia": "Neurologist",
  "bell's palsy": "Neurologist",
  "cerebral palsy": "Neurologist",
  "brain fog": "Neurologist",
  "narcolepsy": "Neurologist",
  "restless leg syndrome": "Neurologist",
  "transient ischemic attack": "Neurologist",
  "tia": "Neurologist",
  "mini-stroke": "Neurologist",
  "brain aneurysm": "Neurologist",
  "intracranial hemorrhage": "Neurologist",
  "encephalopathy": "Neurologist",
  "spinal cord compression": "Neurologist",
  "cauda equina syndrome": "Neurologist",
  
  // Advanced Cardiovascular conditions
  "aortic aneurysm": "Cardiologist",
  "aortic dissection": "Cardiologist",
  "cardiomyopathy": "Cardiologist",
  "dilated cardiomyopathy": "Cardiologist",
  "hypertrophic cardiomyopathy": "Cardiologist",
  "restrictive cardiomyopathy": "Cardiologist",
  "pericarditis": "Cardiologist",
  "pericardial effusion": "Cardiologist",
  "cardiac tamponade": "Cardiologist",
  "myocarditis": "Cardiologist",
  "endocarditis": "Cardiologist",
  "valvular heart disease": "Cardiologist",
  "mitral valve prolapse": "Cardiologist",
  "aortic stenosis": "Cardiologist",
  "mitral stenosis": "Cardiologist",
  "aortic regurgitation": "Cardiologist",
  "mitral regurgitation": "Cardiologist",
  "tricuspid regurgitation": "Cardiologist",
  "ventricular septal defect": "Cardiologist",
  "vsd": "Cardiologist",
  "atrial septal defect": "Cardiologist",
  "asd": "Cardiologist",
  "patent ductus arteriosus": "Cardiologist",
  "pda": "Cardiologist",
  "tetralogy of fallot": "Cardiologist",
  "coarctation of the aorta": "Cardiologist",
  "pulmonary_hypertension_cardio": "Cardiologist",
  "ventricular tachycardia": "Cardiologist",
  "supraventricular tachycardia": "Cardiologist",
  "svt": "Cardiologist",
  "wolff-parkinson-white syndrome": "Cardiologist",
  "wpw": "Cardiologist",
  "brugada syndrome": "Cardiologist",
  "long qt syndrome": "Cardiologist",
  "sick sinus syndrome": "Cardiologist",
  "prinzmetal angina": "Cardiologist",
  "variant angina": "Cardiologist",
  "cardiac arrest": "Cardiologist",
  "sudden cardiac death": "Cardiologist",
  
  // Advanced Pulmonary conditions
  "pulmonary embolism": "Pulmonologist",
  "pe": "Pulmonologist",
  "pulmonary edema": "Pulmonologist",
  "acute respiratory distress syndrome": "Pulmonologist",
  "ards": "Pulmonologist",
  "interstitial lung disease": "Pulmonologist",
  "ild": "Pulmonologist",
  "idiopathic pulmonary fibrosis": "Pulmonologist",
  "ipf": "Pulmonologist",
  "sarcoidosis": "Pulmonologist",
  "pneumoconiosis": "Pulmonologist",
  "black lung disease": "Pulmonologist",
  "silicosis": "Pulmonologist",
  "asbestosis": "Pulmonologist",
  "hypersensitivity pneumonitis": "Pulmonologist",
  "bronchiectasis": "Pulmonologist",
  "cystic fibrosis": "Pulmonologist",
  "cf": "Pulmonologist",
  "alpha-1 antitrypsin deficiency": "Pulmonologist",
  "pulmonary_hypertension_pulmo": "Pulmonologist",
  "cor pulmonale": "Pulmonologist",
  "pleural effusion": "Pulmonologist",
  "pneumothorax": "Pulmonologist",
  "collapsed lung": "Pulmonologist",
  "hemothorax": "Pulmonologist",
  "pleurisy": "Pulmonologist",
  "empyema": "Pulmonologist",
  "lung abscess": "Pulmonologist",
  "obstructive sleep apnea": "Pulmonologist",
  "osa": "Pulmonologist",
  "central sleep apnea": "Pulmonologist",
  "pickwickian syndrome": "Pulmonologist",
  "obesity hypoventilation syndrome": "Pulmonologist",
  
  // Advanced Gastroenterological conditions
  "barrett's esophagus": "Gastroenterologist",
  "esophageal varices": "Gastroenterologist",
  "mallory-weiss tear": "Gastroenterologist",
  "esophageal stricture": "Gastroenterologist",
  "achalasia": "Gastroenterologist",
  "gastroparesis": "Gastroenterologist",
  "zollinger-ellison syndrome": "Gastroenterologist",
  "gastric ulcer": "Gastroenterologist",
  "duodenal ulcer": "Gastroenterologist",
  "peptic ulcer disease": "Gastroenterologist",
  "pud": "Gastroenterologist",
  "helicobacter pylori": "Gastroenterologist",
  "h. pylori": "Gastroenterologist",
  "gastritis": "Gastroenterologist",
  "small intestinal bacterial overgrowth": "Gastroenterologist",
  "sibo": "Gastroenterologist",
  "malabsorption syndrome": "Gastroenterologist",
  "short bowel syndrome": "Gastroenterologist",
  "intestinal obstruction": "Gastroenterologist",
  "ileus": "Gastroenterologist",
  "volvulus": "Gastroenterologist",
  "intussusception": "Gastroenterologist",
  "diverticulosis": "Gastroenterologist",
  "diverticular disease": "Gastroenterologist",
  "microscopic colitis": "Gastroenterologist",
  "collagenous colitis": "Gastroenterologist",
  "lymphocytic colitis": "Gastroenterologist",
  "pseudomembranous colitis": "Gastroenterologist",
  "c. difficile colitis": "Gastroenterologist",
  "toxic megacolon": "Gastroenterologist",
  "anal_fissure": "Gastroenterologist",
  "anal_fistula": "Gastroenterologist",
  "perianal abscess": "Gastroenterologist",
  "fecal impaction": "Gastroenterologist",
  "primary biliary cholangitis": "Gastroenterologist",
  "pbc": "Gastroenterologist",
  "primary sclerosing cholangitis": "Gastroenterologist",
  "psc": "Gastroenterologist",
  "autoimmune hepatitis": "Gastroenterologist",
  "nonalcoholic fatty liver disease": "Gastroenterologist",
  "nafld": "Gastroenterologist",
  "nonalcoholic steatohepatitis": "Gastroenterologist",
  "nash": "Gastroenterologist",
  "alcoholic liver disease": "Gastroenterologist",
  "ald": "Gastroenterologist",
  "hepatic encephalopathy": "Gastroenterologist",
  "portal hypertension": "Gastroenterologist",
  "ascites": "Gastroenterologist",
  "spontaneous bacterial peritonitis": "Gastroenterologist",
  "sbp": "Gastroenterologist",
  "hepatorenal syndrome": "Gastroenterologist",
  "cholecystitis": "Gastroenterologist",
  "choledocholithiasis": "Gastroenterologist",
  "bile duct stones": "Gastroenterologist",
  "cholangitis": "Gastroenterologist",
  "sphincter of oddi dysfunction": "Gastroenterologist",
  "pancreatic pseudocyst": "Gastroenterologist",
  "pancreatic cancer": "Gastroenterologist",
  
  // Advanced Dermatological conditions
  "atopic dermatitis": "Dermatologist",
  "contact dermatitis": "Dermatologist",
  "seborrheic dermatitis": "Dermatologist",
  "nummular dermatitis": "Dermatologist",
  "stasis dermatitis": "Dermatologist",
  "dyshidrotic eczema": "Dermatologist",
  "pompholyx": "Dermatologist",
  "lichen planus": "Dermatologist",
  "lichen simplex chronicus": "Dermatologist",
  "pityriasis rosea": "Dermatologist",
  "pityriasis rubra pilaris": "Dermatologist",
  "prurigo nodularis": "Dermatologist",
  "pemphigus vulgaris": "Dermatologist",
  "bullous pemphigoid": "Dermatologist",
  "dermatitis herpetiformis": "Dermatologist",
  "hidradenitis suppurativa": "Dermatologist",
  "folliculitis": "Dermatologist",
  "furunculosis": "Dermatologist",
  "carbuncle": "Dermatologist",
  "cellulitis": "Dermatologist",
  "erysipelas": "Dermatologist",
  "impetigo": "Dermatologist",
  "molluscum contagiosum": "Dermatologist",
  "tinea corporis": "Dermatologist",
  "ringworm": "Dermatologist",
  "tinea pedis": "Dermatologist",
  "athlete's foot": "Dermatologist",
  "tinea cruris": "Dermatologist",
  "jock itch": "Dermatologist",
  "tinea versicolor": "Dermatologist",
  "pityriasis versicolor": "Dermatologist",
  "onychomycosis": "Dermatologist",
  "nail fungus": "Dermatologist",
  "scabies": "Dermatologist",
  "pediculosis": "Dermatologist",
  "lice": "Dermatologist",
  "urticaria": "Dermatologist",
  "angioedema": "Dermatologist",
  "erythema multiforme": "Dermatologist",
  "erythema nodosum": "Dermatologist",
  "stevens-johnson syndrome": "Dermatologist",
  "sjs": "Dermatologist",
  "toxic epidermal necrolysis": "Dermatologist",
  "ten": "Dermatologist",
  "actinic keratosis": "Dermatologist",
  "basal cell carcinoma": "Dermatologist",
  "bcc": "Dermatologist",
  "squamous cell carcinoma": "Dermatologist",
  "scc": "Dermatologist",
  "merkel cell carcinoma": "Dermatologist",
  "kaposi sarcoma": "Dermatologist",
  "seborrheic keratosis": "Dermatologist",
  "keratoacanthoma": "Dermatologist",
  "cherry angioma": "Dermatologist",
  "pyogenic granuloma": "Dermatologist",
  "keloid": "Dermatologist",
  "hypertrophic scar": "Dermatologist",
  "alopecia areata": "Dermatologist",
  "telogen effluvium": "Dermatologist",
  "androgenetic alopecia": "Dermatologist",
  "male pattern baldness": "Dermatologist",
  "female pattern hair loss": "Dermatologist",
  "hirsutism": "Dermatologist",
  "hyperhidrosis": "Dermatologist",
  "miliaria": "Dermatologist",
  "heat rash": "Dermatologist",
  
  // Advanced Rheumatological conditions
  "polymyositis": "Rheumatologist",
  "dermatomyositis": "Rheumatologist",
  "inclusion body myositis": "Rheumatologist",
  "polymyalgia rheumatica": "Rheumatologist",
  "giant cell arteritis": "Rheumatologist",
  "temporal arteritis": "Rheumatologist",
  "takayasu arteritis": "Rheumatologist",
  "polyarteritis nodosa": "Rheumatologist",
  "granulomatosis with polyangiitis": "Rheumatologist",
  "wegener's granulomatosis": "Rheumatologist",
  "microscopic polyangiitis": "Rheumatologist",
  "eosinophilic granulomatosis with polyangiitis": "Rheumatologist",
  "churg-strauss syndrome": "Rheumatologist",
  "behcet's disease": "Rheumatologist",
  "mixed connective tissue disease": "Rheumatologist",
  "mctd": "Rheumatologist",
  "undifferentiated connective tissue disease": "Rheumatologist",
  "uctd": "Rheumatologist",
  "relapsing polychondritis": "Rheumatologist",
  "cryoglobulinemia": "Rheumatologist",
  "antiphospholipid syndrome": "Rheumatologist",
  "aps": "Rheumatologist",
  "reactive arthritis": "Rheumatologist",
  "reiter's syndrome": "Rheumatologist",
  "enteropathic arthritis": "Rheumatologist",
  "juvenile idiopathic arthritis": "Rheumatologist",
  "jia": "Rheumatologist",
  "adult-onset still's disease": "Rheumatologist",
  "aosd": "Rheumatologist",
  "palindromic rheumatism": "Rheumatologist",
  "crystalline arthropathy": "Rheumatologist",
  "calcium pyrophosphate deposition disease": "Rheumatologist",
  "cppd": "Rheumatologist",
  "pseudogout": "Rheumatologist",
  "hydroxyapatite crystal deposition disease": "Rheumatologist",
  "milwaukee shoulder syndrome": "Rheumatologist",
  "diffuse idiopathic skeletal hyperostosis": "Rheumatologist",
  "dish": "Rheumatologist",
  "fibromyalgia": "Rheumatologist",
  "myofascial pain syndrome": "Rheumatologist",
  
  // Advanced Endocrinological conditions
  "type 1 diabetes": "Endocrinologist",
  "type 2 diabetes": "Endocrinologist",
  "gestational diabetes": "Endocrinologist",
  "diabetic ketoacidosis": "Endocrinologist",
  "dka": "Endocrinologist",
  "hyperosmolar hyperglycemic state": "Endocrinologist",
  "hhs": "Endocrinologist",
  "diabetic neuropathy": "Endocrinologist",
  "diabetic retinopathy": "Endocrinologist",
  "diabetic nephropathy": "Endocrinologist",
  "graves' disease": "Endocrinologist",
  "hashimoto's thyroiditis": "Endocrinologist",
  "subacute thyroiditis": "Endocrinologist",
  "de quervain's thyroiditis": "Endocrinologist",
  "postpartum thyroiditis": "Endocrinologist",
  "toxic multinodular goiter": "Endocrinologist",
  "toxic adenoma": "Endocrinologist",
  "thyroid nodule": "Endocrinologist",
  "thyroid cancer": "Endocrinologist",
  "thyroid storm": "Endocrinologist",
  "myxedema coma": "Endocrinologist",
  "adrenal insufficiency": "Endocrinologist",
  "addison's disease": "Endocrinologist",
  "cushing's syndrome": "Endocrinologist",
  "cushing's disease": "Endocrinologist",
  "conn's syndrome": "Endocrinologist",
  "primary hyperaldosteronism": "Endocrinologist",
  "pheochromocytoma": "Endocrinologist",
  "multiple endocrine neoplasia": "Endocrinologist",
  "men": "Endocrinologist",
  "acromegaly": "Endocrinologist",
  "gigantism": "Endocrinologist",
  "hypopituitarism": "Endocrinologist",
  "panhypopituitarism": "Endocrinologist",
  "diabetes insipidus": "Endocrinologist",
  "syndrome of inappropriate antidiuretic hormone": "Endocrinologist",
  "siadh": "Endocrinologist",
  "hyperparathyroidism": "Endocrinologist",
  "hypoparathyroidism": "Endocrinologist",
  "osteomalacia": "Endocrinologist",
  "rickets": "Endocrinologist",
  "hypercalcemia": "Endocrinologist",
  "hypocalcemia": "Endocrinologist",
  "hypogonadism": "Endocrinologist",
  "klinefelter syndrome": "Endocrinologist",
  "turner syndrome": "Endocrinologist",
  "polycystic_ovary_syndrome": "Endocrinologist",
  "pcos_endocrine": "Endocrinologist",
  "hirsutism_endocrine": "Endocrinologist",
  "gynecomastia": "Endocrinologist",
  "precocious puberty": "Endocrinologist",
  "delayed puberty": "Endocrinologist",
  "amenorrhea": "Endocrinologist",
  "galactorrhea": "Endocrinologist",
  "hyperprolactinemia": "Endocrinologist",
  
  // Advanced Nephrological conditions
  "acute kidney injury": "Nephrologist",
  "aki": "Nephrologist",
  "chronic kidney disease": "Nephrologist",
  "ckd": "Nephrologist",
  "end-stage renal disease": "Nephrologist",
  "esrd": "Nephrologist",
  "nephrotic syndrome": "Nephrologist",
  "minimal change disease": "Nephrologist",
  "focal segmental glomerulosclerosis": "Nephrologist",
  "fsgs": "Nephrologist",
  "membranous nephropathy": "Nephrologist",
  "membranoproliferative glomerulonephritis": "Nephrologist",
  "mpgn": "Nephrologist",
  "iga nephropathy": "Nephrologist",
  "berger's disease": "Nephrologist",
  "alport syndrome": "Nephrologist",
  "goodpasture syndrome": "Nephrologist",
  "anti-gbm disease": "Nephrologist",
  "lupus nephritis": "Nephrologist",
  "rapidly progressive glomerulonephritis": "Nephrologist",
  "rpgn": "Nephrologist",
  "post-streptococcal glomerulonephritis": "Nephrologist",
  "hemolytic uremic syndrome": "Nephrologist",
  "hus": "Nephrologist",
  "thrombotic thrombocytopenic purpura": "Nephrologist",
  "ttp": "Nephrologist",
  "renal tubular acidosis": "Nephrologist",
  "rta": "Nephrologist",
  "bartter syndrome": "Nephrologist",
  "gitelman syndrome": "Nephrologist",
  "liddle syndrome": "Nephrologist",
  "fanconi syndrome": "Nephrologist",
  "renal artery stenosis": "Nephrologist",
  "renal vein thrombosis": "Nephrologist",
  "nephrosclerosis": "Nephrologist",
  "renal osteodystrophy": "Nephrologist",
  "uremic encephalopathy": "Nephrologist",
  "uremic pericarditis": "Nephrologist",
  "hemodialysis complications": "Nephrologist",
  "peritoneal dialysis complications": "Nephrologist",
  "kidney transplant rejection": "Nephrologist",
  "post-transplant lymphoproliferative disorder": "Nephrologist",
  "ptld": "Nephrologist"
};

/**
 * Combines the basic and advanced symptom mappings
 * @returns Combined symptom to specialty mapping
 */
export function getCombinedSymptomMapping(): SymptomMapping {
  const { symptomToSpecialtyMapping } = require('./symptomMapping');
  return { ...symptomToSpecialtyMapping, ...advancedSymptomToSpecialtyMapping };
}

/**
 * Advanced specialty finder that uses both basic and advanced symptom mappings
 * @param symptoms - String containing patient's symptoms
 * @returns The most appropriate medical specialty
 */
export function findSpecialtyAdvanced(symptoms: string): string {
  const lowerSymptoms = symptoms.toLowerCase();
  let detectedSpecialty = "General Physician"; // Default
  
  // Get combined mapping
  const combinedMapping = getCombinedSymptomMapping();
  
  // Check symptoms against our mapping
  for (const [symptom, specialty] of Object.entries(combinedMapping)) {
    if (lowerSymptoms.includes(symptom)) {
      detectedSpecialty = specialty;
      break;
    }
  }
  
  return detectedSpecialty;
}
