/**
 * Comprehensive symptom-to-specialty mapping
 * This file contains an extensive mapping of medical symptoms to appropriate medical specialties
 * Data compiled from medical resources and clinical guidelines
 */

export interface SymptomMapping {
    [symptom: string]: string;
  }
  
  export const symptomToSpecialtyMapping: SymptomMapping = {
    // Neurological symptoms
    "headache": "Neurologist",
    "migraine": "Neurologist",
    "dizziness": "Neurologist",
    "vertigo": "Neurologist",
    "seizure": "Neurologist",
    "tremor": "Neurologist",
    "memory loss": "Neurologist",
    "confusion": "Neurologist",
    "fainting": "Neurologist",
    "numbness": "Neurologist",
    "tingling": "Neurologist",
    "weakness": "Neurologist",
    "paralysis": "Neurologist",
    "difficulty speaking": "Neurologist",
    "slurred speech": "Neurologist",
    "balance problems": "Neurologist",
    "coordination problems": "Neurologist",
    "stroke": "Neurologist",
    "epilepsy": "Neurologist",
    "multiple sclerosis": "Neurologist",
    "parkinson": "Neurologist",
    "alzheimer": "Neurologist",
    "dementia": "Neurologist",
    "nerve pain": "Neurologist",
    "neuropathy": "Neurologist",
    
    // Dental symptoms
    "tooth": "Dentist",
    "teeth": "Dentist",
    "gum": "Dentist",
    "toothache": "Dentist",
    "dental pain": "Dentist",
    "cavity": "Dentist",
    "bleeding gums": "Dentist",
    "swollen gums": "Dentist",
    "sensitive teeth": "Dentist",
    "bad breath": "Dentist",
    "mouth sore": "Dentist",
    "jaw pain": "Dentist",
    "loose tooth": "Dentist",
    "broken tooth": "Dentist",
    "tooth decay": "Dentist",
    "tooth abscess": "Dentist",
    "wisdom tooth": "Dentist",
    "grinding teeth": "Dentist",
    "dry socket": "Dentist",
    "mouth ulcer": "Dentist",
    
    // Cardiovascular symptoms
    "chest pain": "Cardiologist",
    "heart": "Cardiologist",
    "palpitation": "Cardiologist",
    "heart palpitations": "Cardiologist",
    "rapid heartbeat": "Cardiologist",
    "irregular heartbeat": "Cardiologist",
    "high blood pressure": "Cardiologist",
    "hypertension": "Cardiologist",
    "low blood pressure": "Cardiologist",
    "hypotension": "Cardiologist",
    "shortness of breath": "Cardiologist",
    "heart attack": "Cardiologist",
    "angina": "Cardiologist",
    "heart failure": "Cardiologist",
    "heart murmur": "Cardiologist",
    "arrhythmia": "Cardiologist",
    "atrial fibrillation": "Cardiologist",
    "coronary artery disease": "Cardiologist",
    "heart valve disease": "Cardiologist",
    "swelling in legs": "Cardiologist",
    "edema": "Cardiologist",
    "cyanosis": "Cardiologist",
    "high cholesterol": "Cardiologist",
    "hyperlipidemia": "Cardiologist",
    
    // Dermatological symptoms
    "skin": "Dermatologist",
    "rash": "Dermatologist",
    "acne": "Dermatologist",
    "eczema": "Dermatologist",
    "psoriasis": "Dermatologist",
    "hives": "Dermatologist",
    "itching": "Dermatologist",
    "mole": "Dermatologist",
    "wart": "Dermatologist",
    "skin lesion": "Dermatologist",
    "skin cancer": "Dermatologist",
    "melanoma": "Dermatologist",
    "skin infection": "Dermatologist",
    "fungal infection": "Dermatologist",
    "dermatitis": "Dermatologist",
    "dry skin": "Dermatologist",
    "excessive sweating": "Dermatologist",
    "hyperhidrosis": "Dermatologist",
    "hair loss": "Dermatologist",
    "alopecia": "Dermatologist",
    "dandruff": "Dermatologist",
    "skin discoloration": "Dermatologist",
    "vitiligo": "Dermatologist",
    "rosacea": "Dermatologist",
    
    // Orthopedic symptoms
    "bone": "Orthopedic",
    "joint pain": "Orthopedic",
    "back pain": "Orthopedic",
    "fracture": "Orthopedic",
    "broken bone": "Orthopedic",
    "sprain": "Orthopedic",
    "strain": "Orthopedic",
    "arthritis": "Orthopedic",
    "osteoarthritis": "Orthopedic",
    "rheumatoid arthritis": "Orthopedic",
    "gout": "Orthopedic",
    "bursitis": "Orthopedic",
    "tendonitis": "Orthopedic",
    "carpal tunnel": "Orthopedic",
    "knee pain": "Orthopedic",
    "hip pain": "Orthopedic",
    "shoulder pain": "Orthopedic",
    "neck pain": "Orthopedic",
    "sciatica": "Orthopedic",
    "herniated disc": "Orthopedic",
    "scoliosis": "Orthopedic",
    "osteoporosis": "Orthopedic",
    "sports injury": "Orthopedic",
    "joint stiffness": "Orthopedic",
    "muscle pain": "Orthopedic",
    
    // General medicine symptoms
    "flu": "General Physician",
    "fever": "General Physician",
    "cold": "General Physician",
    "cough": "General Physician",
    "sore throat": "General Physician",
    "runny nose": "General Physician",
    "nasal congestion": "General Physician",
    "sneezing": "General Physician",
    "fatigue": "General Physician",
    "tiredness": "General Physician",
    "body ache": "General Physician",
    "muscle ache": "General Physician",
    "chills": "General Physician",
    "nausea": "General Physician",
    "vomiting": "General Physician",
    "diarrhea": "General Physician",
    "constipation": "General Physician",
    "indigestion": "General Physician",
    "heartburn": "General Physician",
    "stomach pain": "General Physician",
    "abdominal pain": "General Physician",
    "headache": "General Physician",
    "weight loss": "General Physician",
    "weight gain": "General Physician",
    "loss of appetite": "General Physician",
    
    // Gastroenterology symptoms
    "stomach": "Gastroenterologist",
    "abdominal pain": "Gastroenterologist",
    "bloating": "Gastroenterologist",
    "gas": "Gastroenterologist",
    "indigestion": "Gastroenterologist",
    "heartburn": "Gastroenterologist",
    "acid reflux": "Gastroenterologist",
    "GERD": "Gastroenterologist",
    "difficulty swallowing": "Gastroenterologist",
    "dysphagia": "Gastroenterologist",
    "nausea": "Gastroenterologist",
    "vomiting": "Gastroenterologist",
    "diarrhea": "Gastroenterologist",
    "constipation": "Gastroenterologist",
    "blood in stool": "Gastroenterologist",
    "rectal bleeding": "Gastroenterologist",
    "jaundice": "Gastroenterologist",
    "hepatitis": "Gastroenterologist",
    "cirrhosis": "Gastroenterologist",
    "gallstones": "Gastroenterologist",
    "pancreatitis": "Gastroenterologist",
    "ulcer": "Gastroenterologist",
    "crohn's disease": "Gastroenterologist",
    "ulcerative colitis": "Gastroenterologist",
    "irritable bowel syndrome": "Gastroenterologist",
    "IBS": "Gastroenterologist",
    "celiac disease": "Gastroenterologist",
    
    // ENT (Ear, Nose, Throat) symptoms
    "ear pain": "ENT Specialist",
    "earache": "ENT Specialist",
    "ear infection": "ENT Specialist",
    "hearing loss": "ENT Specialist",
    "tinnitus": "ENT Specialist",
    "ringing in ears": "ENT Specialist",
    "ear discharge": "ENT Specialist",
    "ear wax": "ENT Specialist",
    "nose bleed": "ENT Specialist",
    "nasal congestion": "ENT Specialist",
    "runny nose": "ENT Specialist",
    "sinusitis": "ENT Specialist",
    "sinus pain": "ENT Specialist",
    "sinus pressure": "ENT Specialist",
    "sore throat": "ENT Specialist",
    "throat pain": "ENT Specialist",
    "hoarseness": "ENT Specialist",
    "voice change": "ENT Specialist",
    "difficulty swallowing": "ENT Specialist",
    "tonsillitis": "ENT Specialist",
    "snoring": "ENT Specialist",
    "sleep apnea": "ENT Specialist",
    "vertigo": "ENT Specialist",
    "dizziness": "ENT Specialist",
    "balance problems": "ENT Specialist",
    
    // Ophthalmology symptoms
    "eye": "Ophthalmologist",
    "vision": "Ophthalmologist",
    "eye pain": "Ophthalmologist",
    "eye redness": "Ophthalmologist",
    "blurry vision": "Ophthalmologist",
    "double vision": "Ophthalmologist",
    "vision loss": "Ophthalmologist",
    "floaters": "Ophthalmologist",
    "flashes of light": "Ophthalmologist",
    "dry eyes": "Ophthalmologist",
    "watery eyes": "Ophthalmologist",
    "itchy eyes": "Ophthalmologist",
    "eye discharge": "Ophthalmologist",
    "sensitivity to light": "Ophthalmologist",
    "photophobia": "Ophthalmologist",
    "eye strain": "Ophthalmologist",
    "cataracts": "Ophthalmologist",
    "glaucoma": "Ophthalmologist",
    "macular degeneration": "Ophthalmologist",
    "stye": "Ophthalmologist",
    "conjunctivitis": "Ophthalmologist",
    "pink eye": "Ophthalmologist",
    "color blindness": "Ophthalmologist",
    "night blindness": "Ophthalmologist",
    
    // Urology symptoms
    "urinary": "Urologist",
    "bladder": "Urologist",
    "kidney": "Urologist",
    "frequent urination": "Urologist",
    "painful urination": "Urologist",
    "burning urination": "Urologist",
    "blood in urine": "Urologist",
    "hematuria": "Urologist",
    "urinary incontinence": "Urologist",
    "urinary retention": "Urologist",
    "kidney stone": "Urologist",
    "kidney pain": "Urologist",
    "flank pain": "Urologist",
    "prostate": "Urologist",
    "erectile dysfunction": "Urologist",
    "testicular pain": "Urologist",
    "testicular swelling": "Urologist",
    "urinary tract infection": "Urologist",
    "UTI": "Urologist",
    "bladder infection": "Urologist",
    "interstitial cystitis": "Urologist",
    "overactive bladder": "Urologist",
    
    // Gynecology symptoms
    "menstrual": "Gynecologist",
    "period": "Gynecologist",
    "vaginal": "Gynecologist",
    "pelvic pain": "Gynecologist",
    "menstrual pain": "Gynecologist",
    "menstrual cramps": "Gynecologist",
    "irregular periods": "Gynecologist",
    "heavy periods": "Gynecologist",
    "missed period": "Gynecologist",
    "vaginal discharge": "Gynecologist",
    "vaginal itching": "Gynecologist",
    "vaginal odor": "Gynecologist",
    "vaginal dryness": "Gynecologist",
    "vaginal bleeding": "Gynecologist",
    "breast pain": "Gynecologist",
    "breast lump": "Gynecologist",
    "nipple discharge": "Gynecologist",
    "pregnancy": "Gynecologist",
    "fertility issues": "Gynecologist",
    "infertility": "Gynecologist",
    "endometriosis": "Gynecologist",
    "polycystic ovary syndrome": "Gynecologist",
    "PCOS": "Gynecologist",
    "menopause": "Gynecologist",
    "hot flashes": "Gynecologist",
    
    // Pulmonology symptoms
    "lung": "Pulmonologist",
    "breathing": "Pulmonologist",
    "shortness of breath": "Pulmonologist",
    "difficulty breathing": "Pulmonologist",
    "wheezing": "Pulmonologist",
    "chronic cough": "Pulmonologist",
    "coughing up blood": "Pulmonologist",
    "hemoptysis": "Pulmonologist",
    "chest congestion": "Pulmonologist",
    "chest tightness": "Pulmonologist",
    "asthma": "Pulmonologist",
    "COPD": "Pulmonologist",
    "emphysema": "Pulmonologist",
    "chronic bronchitis": "Pulmonologist",
    "pneumonia": "Pulmonologist",
    "tuberculosis": "Pulmonologist",
    "TB": "Pulmonologist",
    "pulmonary fibrosis": "Pulmonologist",
    "pulmonary embolism": "Pulmonologist",
    "sleep apnea": "Pulmonologist",
    "lung cancer": "Pulmonologist",
    "pleural effusion": "Pulmonologist",
    
    // Endocrinology symptoms
    "diabetes": "Endocrinologist",
    "thyroid": "Endocrinologist",
    "hormone": "Endocrinologist",
    "excessive thirst": "Endocrinologist",
    "polydipsia": "Endocrinologist",
    "frequent urination": "Endocrinologist",
    "polyuria": "Endocrinologist",
    "weight changes": "Endocrinologist",
    "fatigue": "Endocrinologist",
    "heat intolerance": "Endocrinologist",
    "cold intolerance": "Endocrinologist",
    "hair loss": "Endocrinologist",
    "excessive sweating": "Endocrinologist",
    "tremor": "Endocrinologist",
    "goiter": "Endocrinologist",
    "hyperthyroidism": "Endocrinologist",
    "hypothyroidism": "Endocrinologist",
    "adrenal": "Endocrinologist",
    "cushing syndrome": "Endocrinologist",
    "addison disease": "Endocrinologist",
    "pituitary": "Endocrinologist",
    "growth problems": "Endocrinologist",
    "metabolic syndrome": "Endocrinologist",
    
    // Nephrology symptoms
    "kidney": "Nephrologist",
    "kidney disease": "Nephrologist",
    "kidney failure": "Nephrologist",
    "renal failure": "Nephrologist",
    "blood in urine": "Nephrologist",
    "hematuria": "Nephrologist",
    "protein in urine": "Nephrologist",
    "proteinuria": "Nephrologist",
    "swelling": "Nephrologist",
    "edema": "Nephrologist",
    "high blood pressure": "Nephrologist",
    "hypertension": "Nephrologist",
    "kidney stones": "Nephrologist",
    "nephrolithiasis": "Nephrologist",
    "dialysis": "Nephrologist",
    "glomerulonephritis": "Nephrologist",
    "polycystic kidney disease": "Nephrologist",
    "PKD": "Nephrologist",
    
    // Rheumatology symptoms
    "joint pain": "Rheumatologist",
    "joint swelling": "Rheumatologist",
    "joint stiffness": "Rheumatologist",
    "arthritis": "Rheumatologist",
    "rheumatoid arthritis": "Rheumatologist",
    "lupus": "Rheumatologist",
    "SLE": "Rheumatologist",
    "fibromyalgia": "Rheumatologist",
    "gout": "Rheumatologist",
    "scleroderma": "Rheumatologist",
    "vasculitis": "Rheumatologist",
    "ankylosing spondylitis": "Rheumatologist",
    "psoriatic arthritis": "Rheumatologist",
    "polymyalgia rheumatica": "Rheumatologist",
    "sjogren syndrome": "Rheumatologist",
    "osteoarthritis": "Rheumatologist",
    "bursitis": "Rheumatologist",
    "tendonitis": "Rheumatologist",
    
    // Hematology symptoms
    "anemia": "Hematologist",
    "blood": "Hematologist",
    "bleeding": "Hematologist",
    "bruising": "Hematologist",
    "fatigue": "Hematologist",
    "weakness": "Hematologist",
    "pale skin": "Hematologist",
    "pallor": "Hematologist",
    "swollen lymph nodes": "Hematologist",
    "lymphadenopathy": "Hematologist",
    "leukemia": "Hematologist",
    "lymphoma": "Hematologist",
    "multiple myeloma": "Hematologist",
    "hemophilia": "Hematologist",
    "sickle cell": "Hematologist",
    "thalassemia": "Hematologist",
    "iron deficiency": "Hematologist",
    "blood clot": "Hematologist",
    "thrombosis": "Hematologist",
    "bleeding disorder": "Hematologist",
    
    // Oncology symptoms
    "cancer": "Oncologist",
    "tumor": "Oncologist",
    "mass": "Oncologist",
    "lump": "Oncologist",
    "unexplained weight loss": "Oncologist",
    "fatigue": "Oncologist",
    "night sweats": "Oncologist",
    "persistent pain": "Oncologist",
    "change in bowel habits": "Oncologist",
    "change in bladder habits": "Oncologist",
    "unusual bleeding": "Oncologist",
    "unusual discharge": "Oncologist",
    "difficulty swallowing": "Oncologist",
    "persistent cough": "Oncologist",
    "skin changes": "Oncologist",
    "breast cancer": "Oncologist",
    "lung cancer": "Oncologist",
    "colon cancer": "Oncologist",
    "prostate cancer": "Oncologist",
    "leukemia": "Oncologist",
    "lymphoma": "Oncologist",
    
    // Psychiatry symptoms
    "depression": "Psychiatrist",
    "anxiety": "Psychiatrist",
    "panic attack": "Psychiatrist",
    "mood swings": "Psychiatrist",
    "insomnia": "Psychiatrist",
    "sleep problems": "Psychiatrist",
    "hallucinations": "Psychiatrist",
    "delusions": "Psychiatrist",
    "paranoia": "Psychiatrist",
    "suicidal thoughts": "Psychiatrist",
    "self-harm": "Psychiatrist",
    "eating disorder": "Psychiatrist",
    "anorexia": "Psychiatrist",
    "bulimia": "Psychiatrist",
    "bipolar disorder": "Psychiatrist",
    "schizophrenia": "Psychiatrist",
    "PTSD": "Psychiatrist",
    "OCD": "Psychiatrist",
    "ADHD": "Psychiatrist",
    "addiction": "Psychiatrist",
    "substance abuse": "Psychiatrist",
    "alcoholism": "Psychiatrist",
    
    // Neurosurgery symptoms
    "brain tumor": "Neurosurgeon",
    "brain hemorrhage": "Neurosurgeon",
    "brain aneurysm": "Neurosurgeon",
    "severe head injury": "Neurosurgeon",
    "spinal cord injury": "Neurosurgeon",
    "herniated disc": "Neurosurgeon",
    "spinal stenosis": "Neurosurgeon",
    "hydrocephalus": "Neurosurgeon",
    "brain abscess": "Neurosurgeon",
    "intracranial pressure": "Neurosurgeon",
    "carotid artery disease": "Neurosurgeon",
    "cerebral palsy": "Neurosurgeon",
    "nerve compression": "Neurosurgeon",
    
    // Infectious Disease symptoms
    "infection": "Infectious Disease Specialist",
    "fever": "Infectious Disease Specialist",
    "HIV": "Infectious Disease Specialist",
    "AIDS": "Infectious Disease Specialist",
    "tuberculosis": "Infectious Disease Specialist",
    "TB": "Infectious Disease Specialist",
    "malaria": "Infectious Disease Specialist",
    "hepatitis": "Infectious Disease Specialist",
    "meningitis": "Infectious Disease Specialist",
    "encephalitis": "Infectious Disease Specialist",
    "pneumonia": "Infectious Disease Specialist",
    "sepsis": "Infectious Disease Specialist",
    "MRSA": "Infectious Disease Specialist",
    "lyme disease": "Infectious Disease Specialist",
    "COVID-19": "Infectious Disease Specialist",
    "coronavirus": "Infectious Disease Specialist",
    "influenza": "Infectious Disease Specialist",
    "tropical disease": "Infectious Disease Specialist",
    "parasitic infection": "Infectious Disease Specialist",
    "fungal infection": "Infectious Disease Specialist",
    
    // Allergist/Immunologist symptoms
    "allergy": "Allergist/Immunologist",
    "allergic reaction": "Allergist/Immunologist",
    "hives": "Allergist/Immunologist",
    "rash": "Allergist/Immunologist",
    "itching": "Allergist/Immunologist",
    "swelling": "Allergist/Immunologist",
    "anaphylaxis": "Allergist/Immunologist",
    "food allergy": "Allergist/Immunologist",
    "drug allergy": "Allergist/Immunologist",
    "seasonal allergies": "Allergist/Immunologist",
    "hay fever": "Allergist/Immunologist",
    "allergic rhinitis": "Allergist/Immunologist",
    "asthma": "Allergist/Immunologist",
    "eczema": "Allergist/Immunologist",
    "atopic dermatitis": "Allergist/Immunologist",
    "immune deficiency": "Allergist/Immunologist",
    "recurrent infections": "Allergist/Immunologist",
    "autoimmune disease": "Allergist/Immunologist",
    
    // Pediatrics symptoms (for children)
    "child fever": "Pediatrician",
    "child cough": "Pediatrician",
    "child rash": "Pediatrician",
    "child vomiting": "Pediatrician",
    "child diarrhea": "Pediatrician",
    "child ear pain": "Pediatrician",
    "child sore throat": "Pediatrician",
    "child growth issues": "Pediatrician",
    "child development": "Pediatrician",
    "child behavior": "Pediatrician",
    "child vaccination": "Pediatrician",
    "child immunization": "Pediatrician",
    "child nutrition": "Pediatrician",
    "infant": "Pediatrician",
    "newborn": "Pediatrician",
    "baby": "Pediatrician",
    "toddler": "Pediatrician",
    "childhood illness": "Pediatrician",
    "childhood disease": "Pediatrician",
    
    // Geriatrics symptoms (for elderly)
    "elderly": "Geriatrician",
    "aging": "Geriatrician",
    "dementia": "Geriatrician",
    "alzheimer": "Geriatrician",
    "memory loss": "Geriatrician",
    "falls": "Geriatrician",
    "frailty": "Geriatrician",
    "elder care": "Geriatrician",
    "polypharmacy": "Geriatrician",
    "medication management": "Geriatrician",
    "elder abuse": "Geriatrician",
    "nursing home": "Geriatrician",
    "assisted living": "Geriatrician",
    "mobility issues": "Geriatrician",
    "incontinence": "Geriatrician",
    
    // Plastic Surgery symptoms
    "cosmetic": "Plastic Surgeon",
    "reconstructive": "Plastic Surgeon",
    "scar": "Plastic Surgeon",
    "burn": "Plastic Surgeon",
    "facial deformity": "Plastic Surgeon",
    "birth defect": "Plastic Surgeon",
    "breast reconstruction": "Plastic Surgeon",
    "rhinoplasty": "Plastic Surgeon",
    "facelift": "Plastic Surgeon",
    "liposuction": "Plastic Surgeon",
    "botox": "Plastic Surgeon",
    "filler": "Plastic Surgeon",
    "body contouring": "Plastic Surgeon",
    "skin graft": "Plastic Surgeon",
    
    // Sports Medicine symptoms
    "sports injury": "Sports Medicine Specialist",
    "athletic injury": "Sports Medicine Specialist",
    "muscle strain": "Sports Medicine Specialist",
    "ligament tear": "Sports Medicine Specialist",
    "tendon injury": "Sports Medicine Specialist",
    "concussion": "Sports Medicine Specialist",
    "overuse injury": "Sports Medicine Specialist",
    "runner's knee": "Sports Medicine Specialist",
    "tennis elbow": "Sports Medicine Specialist",
    "golfer's elbow": "Sports Medicine Specialist",
    "shin splints": "Sports Medicine Specialist",
    "stress fracture": "Sports Medicine Specialist",
    "sports performance": "Sports Medicine Specialist",
    "exercise": "Sports Medicine Specialist",
    "fitness": "Sports Medicine Specialist",
    
    // Pain Management symptoms
    "chronic pain": "Pain Management Specialist",
    "back pain": "Pain Management Specialist",
    "neck pain": "Pain Management Specialist",
    "joint pain": "Pain Management Specialist",
    "nerve pain": "Pain Management Specialist",
    "neuropathic pain": "Pain Management Specialist",
    "fibromyalgia": "Pain Management Specialist",
    "complex regional pain syndrome": "Pain Management Specialist",
    "CRPS": "Pain Management Specialist",
    "cancer pain": "Pain Management Specialist",
    "post-surgical pain": "Pain Management Specialist",
    "migraine": "Pain Management Specialist",
    "headache": "Pain Management Specialist",
    "sciatica": "Pain Management Specialist",
    
    // Vascular Surgery symptoms
    "varicose veins": "Vascular Surgeon",
    "spider veins": "Vascular Surgeon",
    "deep vein thrombosis": "Vascular Surgeon",
    "DVT": "Vascular Surgeon",
    "blood clot": "Vascular Surgeon",
    "peripheral artery disease": "Vascular Surgeon",
    "PAD": "Vascular Surgeon",
    "aneurysm": "Vascular Surgeon",
    "carotid artery disease": "Vascular Surgeon",
    "poor circulation": "Vascular Surgeon",
    "leg pain when walking": "Vascular Surgeon",
    "claudication": "Vascular Surgeon",
    "leg ulcer": "Vascular Surgeon",
    "lymphedema": "Vascular Surgeon",
    
    // Colorectal Surgery symptoms
    "colon": "Colorectal Surgeon",
    "rectal": "Colorectal Surgeon",
    "anal": "Colorectal Surgeon",
    "hemorrhoids": "Colorectal Surgeon",
    "piles": "Colorectal Surgeon",
    "anal fissure": "Colorectal Surgeon",
    "anal fistula": "Colorectal Surgeon",
    "rectal bleeding": "Colorectal Surgeon",
    "colorectal cancer": "Colorectal Surgeon",
    "colon cancer": "Colorectal Surgeon",
    "rectal cancer": "Colorectal Surgeon",
    "diverticulitis": "Colorectal Surgeon",
    "inflammatory bowel disease": "Colorectal Surgeon",
    "IBD": "Colorectal Surgeon",
    "crohn's disease": "Colorectal Surgeon",
    "ulcerative colitis": "Colorectal Surgeon",
    "polyps": "Colorectal Surgeon",
    "constipation": "Colorectal Surgeon",
    "fecal incontinence": "Colorectal Surgeon"
  };
  
  /**
   * Helper function to find the most appropriate specialty based on symptoms
   * @param symptoms - String containing patient's symptoms
   * @returns The most appropriate medical specialty
   */
  export function findSpecialty(symptoms: string): string {
    const lowerSymptoms = symptoms.toLowerCase();
    let detectedSpecialty = "General Physician"; // Default
    
    // Check symptoms against our mapping
    for (const [symptom, specialty] of Object.entries(symptomToSpecialtyMapping)) {
      if (lowerSymptoms.includes(symptom)) {
        detectedSpecialty = specialty;
        break;
      }
    }
    
    return detectedSpecialty;
  }